//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoAnalyzer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Code comments should be in English for international team collaboration 的本地化字符串。
        /// </summary>
        internal static string CHN001_Description {
            get {
                return ResourceManager.GetString("CHN001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment contains Chinese characters: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string CHN001_MessageFormat {
            get {
                return ResourceManager.GetString("CHN001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese in comments 的本地化字符串。
        /// </summary>
        internal static string CHN001_Title {
            get {
                return ResourceManager.GetString("CHN001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comments should not contain commented-out code 的本地化字符串。
        /// </summary>
        internal static string CODE001_Description {
            get {
                return ResourceManager.GetString("CODE001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment contains code fragment: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string CODE001_MessageFormat {
            get {
                return ResourceManager.GetString("CODE001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code in comment 的本地化字符串。
        /// </summary>
        internal static string CODE001_Title {
            get {
                return ResourceManager.GetString("CODE001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify DefaultDllImportSearchPaths to prevent DLL hijacking attacks 的本地化字符串。
        /// </summary>
        internal static string DLL002_Description {
            get {
                return ResourceManager.GetString("DLL002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DllImport &apos;{0}&apos; missing DefaultDllImportSearchPaths attribute 的本地化字符串。
        /// </summary>
        internal static string DLL002_MessageFormat {
            get {
                return ResourceManager.GetString("DLL002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing DllImportSearchPaths 的本地化字符串。
        /// </summary>
        internal static string DLL002_Title {
            get {
                return ResourceManager.GetString("DLL002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has invalid or missing signature 的本地化字符串。
        /// </summary>
        internal static string DLL003_Arg_InvalidSig {
            get {
                return ResourceManager.GetString("DLL003_Arg_InvalidSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} not found 的本地化字符串。
        /// </summary>
        internal static string DLL003_Arg_NotFound {
            get {
                return ResourceManager.GetString("DLL003_Arg_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unknown DLL 的本地化字符串。
        /// </summary>
        internal static string DLL003_Arg_Unknown {
            get {
                return ResourceManager.GetString("DLL003_Arg_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Referenced DLLs should have valid digital signatures 的本地化字符串。
        /// </summary>
        internal static string DLL003_Description {
            get {
                return ResourceManager.GetString("DLL003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DLL &apos;{0}&apos; {1} 的本地化字符串。
        /// </summary>
        internal static string DLL003_MessageFormat {
            get {
                return ResourceManager.GetString("DLL003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsafe DLL signature 的本地化字符串。
        /// </summary>
        internal static string DLL003_Title {
            get {
                return ResourceManager.GetString("DLL003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Printing full stack traces may expose internal system structure 的本地化字符串。
        /// </summary>
        internal static string EXC001_Description {
            get {
                return ResourceManager.GetString("EXC001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full stack trace should not be printed in catch block 的本地化字符串。
        /// </summary>
        internal static string EXC001_MessageFormat {
            get {
                return ResourceManager.GetString("EXC001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stack trace in catch 的本地化字符串。
        /// </summary>
        internal static string EXC001_Title {
            get {
                return ResourceManager.GetString("EXC001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sensitive information should not be hardcoded 的本地化字符串。
        /// </summary>
        internal static string SEC001_Description {
            get {
                return ResourceManager.GetString("SEC001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable &apos;{0}&apos; may contain hardcoded sensitive information 的本地化字符串。
        /// </summary>
        internal static string SEC001_MessageFormat {
            get {
                return ResourceManager.GetString("SEC001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sensitive info in code 的本地化字符串。
        /// </summary>
        internal static string SEC001_Title {
            get {
                return ResourceManager.GetString("SEC001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 via string concatenation 的本地化字符串。
        /// </summary>
        internal static string SEC002_Arg_Concat {
            get {
                return ResourceManager.GetString("SEC002_Arg_Concat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 via string interpolation 的本地化字符串。
        /// </summary>
        internal static string SEC002_Arg_Interpolation {
            get {
                return ResourceManager.GetString("SEC002_Arg_Interpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 via {0} method 的本地化字符串。
        /// </summary>
        internal static string SEC002_Arg_Method {
            get {
                return ResourceManager.GetString("SEC002_Arg_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validate and normalize paths to prevent directory traversal attacks 的本地化字符串。
        /// </summary>
        internal static string SEC002_Description {
            get {
                return ResourceManager.GetString("SEC002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File path operation may have path traversal vulnerability 的本地化字符串。
        /// </summary>
        internal static string SEC002_MessageFormat {
            get {
                return ResourceManager.GetString("SEC002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path traversal risk 的本地化字符串。
        /// </summary>
        internal static string SEC002_Title {
            get {
                return ResourceManager.GetString("SEC002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 string concatenation 的本地化字符串。
        /// </summary>
        internal static string SEC003_Arg_Concat {
            get {
                return ResourceManager.GetString("SEC003_Arg_Concat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 string interpolation 的本地化字符串。
        /// </summary>
        internal static string SEC003_Arg_Interpolation {
            get {
                return ResourceManager.GetString("SEC003_Arg_Interpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use parameterized queries to prevent SQL injection 的本地化字符串。
        /// </summary>
        internal static string SEC003_Description {
            get {
                return ResourceManager.GetString("SEC003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL query may be vulnerable to injection 的本地化字符串。
        /// </summary>
        internal static string SEC003_MessageFormat {
            get {
                return ResourceManager.GetString("SEC003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL injection risk 的本地化字符串。
        /// </summary>
        internal static string SEC003_Title {
            get {
                return ResourceManager.GetString("SEC003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TypeNameHandling = {0}, recommend using None 的本地化字符串。
        /// </summary>
        internal static string SEC004_Arg_HandlingRecommend {
            get {
                return ResourceManager.GetString("SEC004_Arg_HandlingRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TypeNameHandling = {0} is unsafe 的本地化字符串。
        /// </summary>
        internal static string SEC004_Arg_HandlingUnsafe {
            get {
                return ResourceManager.GetString("SEC004_Arg_HandlingUnsafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 new {0}() 的本地化字符串。
        /// </summary>
        internal static string SEC004_Arg_NewType {
            get {
                return ResourceManager.GetString("SEC004_Arg_NewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deserializers like BinaryFormatter pose remote code execution risks 的本地化字符串。
        /// </summary>
        internal static string SEC004_Description {
            get {
                return ResourceManager.GetString("SEC004_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using unsafe deserializer: {0} 的本地化字符串。
        /// </summary>
        internal static string SEC004_MessageFormat {
            get {
                return ResourceManager.GetString("SEC004_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsafe deserialization 的本地化字符串。
        /// </summary>
        internal static string SEC004_Title {
            get {
                return ResourceManager.GetString("SEC004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 new Random() is not cryptographically secure 的本地化字符串。
        /// </summary>
        internal static string SEC005_Arg_Construct {
            get {
                return ResourceManager.GetString("SEC005_Arg_Construct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random.{0}() is not cryptographically secure 的本地化字符串。
        /// </summary>
        internal static string SEC005_Arg_MethodCall {
            get {
                return ResourceManager.GetString("SEC005_Arg_MethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use cryptographically secure random number generators for security 的本地化字符串。
        /// </summary>
        internal static string SEC005_Description {
            get {
                return ResourceManager.GetString("SEC005_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System.Random not suitable for security-sensitive scenarios 的本地化字符串。
        /// </summary>
        internal static string SEC005_MessageFormat {
            get {
                return ResourceManager.GetString("SEC005_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insecure random 的本地化字符串。
        /// </summary>
        internal static string SEC005_Title {
            get {
                return ResourceManager.GetString("SEC005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 new Regex() without timeout 的本地化字符串。
        /// </summary>
        internal static string SEC006_Arg_NewRegex {
            get {
                return ResourceManager.GetString("SEC006_Arg_NewRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regex.{0}() without timeout 的本地化字符串。
        /// </summary>
        internal static string SEC006_Arg_StaticRegex {
            get {
                return ResourceManager.GetString("SEC006_Arg_StaticRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set reasonable timeouts for regex operations 的本地化字符串。
        /// </summary>
        internal static string SEC006_Description {
            get {
                return ResourceManager.GetString("SEC006_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regex has no timeout, may cause ReDoS 的本地化字符串。
        /// </summary>
        internal static string SEC006_MessageFormat {
            get {
                return ResourceManager.GetString("SEC006_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regex DoS risk 的本地化字符串。
        /// </summary>
        internal static string SEC006_Title {
            get {
                return ResourceManager.GetString("SEC006_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use &apos;using&apos; statements to ensure proper resource disposal 的本地化字符串。
        /// </summary>
        internal static string SEC007_Description {
            get {
                return ResourceManager.GetString("SEC007_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IDisposable object &apos;{0}&apos; not in using statement 的本地化字符串。
        /// </summary>
        internal static string SEC007_MessageFormat {
            get {
                return ResourceManager.GetString("SEC007_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource leak 的本地化字符串。
        /// </summary>
        internal static string SEC007_Title {
            get {
                return ResourceManager.GetString("SEC007_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 string concatenation may be predictable 的本地化字符串。
        /// </summary>
        internal static string SEC008_Arg_ConcatStructure {
            get {
                return ResourceManager.GetString("SEC008_Arg_ConcatStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 timestamp-based: {0} 的本地化字符串。
        /// </summary>
        internal static string SEC008_Arg_ConcatTimestamp {
            get {
                return ResourceManager.GetString("SEC008_Arg_ConcatTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 string.Format may be predictable 的本地化字符串。
        /// </summary>
        internal static string SEC008_Arg_FormatStructure {
            get {
                return ResourceManager.GetString("SEC008_Arg_FormatStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 predictable interpolation: {0} 的本地化字符串。
        /// </summary>
        internal static string SEC008_Arg_InterpPredictable {
            get {
                return ResourceManager.GetString("SEC008_Arg_InterpPredictable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 string interpolation may be predictable 的本地化字符串。
        /// </summary>
        internal static string SEC008_Arg_InterpStructure {
            get {
                return ResourceManager.GetString("SEC008_Arg_InterpStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 timestamp: {0} 的本地化字符串。
        /// </summary>
        internal static string SEC008_Arg_Timestamp1 {
            get {
                return ResourceManager.GetString("SEC008_Arg_Timestamp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 timestamp: {0} 的本地化字符串。
        /// </summary>
        internal static string SEC008_Arg_Timestamp2 {
            get {
                return ResourceManager.GetString("SEC008_Arg_Timestamp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use secure methods when creating temporary files 的本地化字符串。
        /// </summary>
        internal static string SEC008_Description {
            get {
                return ResourceManager.GetString("SEC008_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temporary file operation may have security issues 的本地化字符串。
        /// </summary>
        internal static string SEC008_MessageFormat {
            get {
                return ResourceManager.GetString("SEC008_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insecure temp file 的本地化字符串。
        /// </summary>
        internal static string SEC008_Title {
            get {
                return ResourceManager.GetString("SEC008_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type.GetType with dynamic input 的本地化字符串。
        /// </summary>
        internal static string SEC009_Arg_GetType {
            get {
                return ResourceManager.GetString("SEC009_Arg_GetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MethodInfo.Invoke on reflected method 的本地化字符串。
        /// </summary>
        internal static string SEC009_Arg_Invoke {
            get {
                return ResourceManager.GetString("SEC009_Arg_Invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} with BindingFlags.NonPublic 的本地化字符串。
        /// </summary>
        internal static string SEC009_Arg_NonPublic {
            get {
                return ResourceManager.GetString("SEC009_Arg_NonPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validate and restrict reflectable types and methods 的本地化字符串。
        /// </summary>
        internal static string SEC009_Description {
            get {
                return ResourceManager.GetString("SEC009_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reflection call uses user-controllable input 的本地化字符串。
        /// </summary>
        internal static string SEC009_MessageFormat {
            get {
                return ResourceManager.GetString("SEC009_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsafe reflection 的本地化字符串。
        /// </summary>
        internal static string SEC009_Title {
            get {
                return ResourceManager.GetString("SEC009_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 check-then-use on field &apos;{0}&apos; without lock 的本地化字符串。
        /// </summary>
        internal static string SEC010_Arg_CheckThenUse {
            get {
                return ResourceManager.GetString("SEC010_Arg_CheckThenUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 collection indexer without lock 的本地化字符串。
        /// </summary>
        internal static string SEC010_Arg_CollectionIndexer {
            get {
                return ResourceManager.GetString("SEC010_Arg_CollectionIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 collection.{0}() without lock 的本地化字符串。
        /// </summary>
        internal static string SEC010_Arg_CollectionMethod {
            get {
                return ResourceManager.GetString("SEC010_Arg_CollectionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 compound assignment ({0}) without lock 的本地化字符串。
        /// </summary>
        internal static string SEC010_Arg_Compound {
            get {
                return ResourceManager.GetString("SEC010_Arg_Compound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 field decrement without lock 的本地化字符串。
        /// </summary>
        internal static string SEC010_Arg_Decrement {
            get {
                return ResourceManager.GetString("SEC010_Arg_Decrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 field increment without lock 的本地化字符串。
        /// </summary>
        internal static string SEC010_Arg_Increment {
            get {
                return ResourceManager.GetString("SEC010_Arg_Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use thread-safe collections in multi-threaded environments 的本地化字符串。
        /// </summary>
        internal static string SEC010_Description {
            get {
                return ResourceManager.GetString("SEC010_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-thread-safe collection &apos;{0}&apos; used in multi-threaded context 的本地化字符串。
        /// </summary>
        internal static string SEC010_MessageFormat {
            get {
                return ResourceManager.GetString("SEC010_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Race condition 的本地化字符串。
        /// </summary>
        internal static string SEC010_Title {
            get {
                return ResourceManager.GetString("SEC010_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BasicHttpBinding without security mode 的本地化字符串。
        /// </summary>
        internal static string SEC011_Arg_BasicHttp {
            get {
                return ResourceManager.GetString("SEC011_Arg_BasicHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 gRPC over HTTP (not HTTPS) 的本地化字符串。
        /// </summary>
        internal static string SEC011_Arg_GrpcHttp {
            get {
                return ResourceManager.GetString("SEC011_Arg_GrpcHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP endpoint (not HTTPS) 的本地化字符串。
        /// </summary>
        internal static string SEC011_Arg_HttpEndpoint {
            get {
                return ResourceManager.GetString("SEC011_Arg_HttpEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} with SecurityMode.None 的本地化字符串。
        /// </summary>
        internal static string SEC011_Arg_SecurityNone {
            get {
                return ResourceManager.GetString("SEC011_Arg_SecurityNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebClient.{0}() over HTTP 的本地化字符串。
        /// </summary>
        internal static string SEC011_Arg_WebClientHttp {
            get {
                return ResourceManager.GetString("SEC011_Arg_WebClientHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use secure binding types for WCF communication 的本地化字符串。
        /// </summary>
        internal static string SEC011_Description {
            get {
                return ResourceManager.GetString("SEC011_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using insecure WCF binding: {0} 的本地化字符串。
        /// </summary>
        internal static string SEC011_MessageFormat {
            get {
                return ResourceManager.GetString("SEC011_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insecure IPC 的本地化字符串。
        /// </summary>
        internal static string SEC011_Title {
            get {
                return ResourceManager.GetString("SEC011_Title", resourceCulture);
            }
        }
    }
}
